name = "my-cloudflare-app"
type = "javascript"

# Set entry point
main = "./app/root.tsx"

# Add compatibility flags if needed
compatibility_date = "2025-03-14"
compatibility_flags = ["nodejs_compat"]
